### ISSUE TITLE
File Sharing: Which file systems are supported?

### ISSUE THREAD

**Issue by porg** [gl-inet/docs3.x#12]
https://docs.gl-inet.com/en/3/app/file_sharing/#samba-smb-support
says nothing about which file systems are supported and how performant on what hardware.

As a Mac user I would like to know whether I could attach a HFS+ disk to one of your wireless AC routers and use it as a network attached storage (NAS) and whether Mac metadata (tags, comments, all timestamps (creation, modification, last viewed, added to folder on), extended attributes like "downloaded from") are properly preserved (if on a real HFS+ disk or a Linux filesystem such as ext4) if the file sharing happens via SMB, as Apple now favors SMB over AFS as of circa 2016.

**Comment by dragon788** [comment]
It is fairly safe to assume that the file system formats supported by the router are primarily ones that have open source components or are available across multiple platforms. In this case FAT32, NTFS, and Ext2/3/4 (Linux). Because ExFAT was only recently open sourced and Apple keeps AFS and HFS pretty close to the vest, those aren't very well supported at all by other operating systems, including the Linux based OpenWRT most of these devices run on.

**Comment by nemanjam** [comment]
I cant choose samba with exFAT.

![image](https://user-images.githubusercontent.com/9990165/207309176-b762056a-decd-4de3-87fd-b7b6a02116b6.png)

**Comment by linmq** [comment]
Please contact support@glinet.biz for the support.

**Comment by nemanjam** [comment]
No need., it works fine, disk wasn't properly formatted.

**Comment by linmq** [comment]
Maybe you can try [network storage](https://docs.gl-inet.com/en/4/tutorials/network_storage/) of firmware v4.x
Please ask tech question on [forum](https://forum.gl-inet.com)
