### ISSUE TITLE
Can mini smart router be an Ethernet router ?

### ISSUE THREAD

**Issue by milouze19** [gl-inet/docs3.x#42]
Hello,
At first, sorry for my bad english and knowledge about all the stuff here :)

I've bought a mini smart router in order of connecting my non-WIFI screen to my box. I want to connect the mini smart router to the box using WIFI (done, I think it works), then connecting the screen by ethernet (doesn't work).
Is the mini smart router is able to do that, and if yes, how :)

Thanks a lot

Milouze

**Comment by linmq** [comment]
Hi, could you move your question to forum.gl-inet.com, there are many support people there. This Issue is for document troubleshooting. Thank you.

You can explain more detail about your GL.iNet router model, and what is the box and no-WiFi screen, maybe some pictures will help us to understand your question.
